app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5434/demospringboot
    username: postgres
    password: 'postgres'
    pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always